name: quilombo
version: 1
content_types:
  - relato
  - evento
  - missao
  - pagina
properties:
  titulo:
    kind: text
    required: true
  descricao:
    kind: text
  slug:
    kind: text
  tags:
    kind: list
  autor:
    kind: text
  publicado:
    kind: checkbox
  data:
    kind: date
  hora:
    kind: text
  local:
    kind: text
  objetivo:
    kind: text
  status:
    kind: text
