use crate::context::{Context, Stage};
use crate::engine::LoggedToolRegistry;
use crate::module::Module;
use std::collections::HashMap;
use std::process::Command;

/// Execute module: issue → PR
/// Creates a branch, uses Claude Code to implement changes, pushes and creates PR.
pub struct ExecuteModule;

impl Module for ExecuteModule {
    fn name(&self) -> &str {
        "execute"
    }

    fn stage(&self) -> Stage {
        Stage::Execute
    }

    fn required_tools(&self) -> Vec<&str> {
        vec!["claude", "github"]
    }

    fn run(&self, ctx: &mut Context, tools: &LoggedToolRegistry) -> anyhow::Result<()> {
        let issue_number = ctx
            .artifacts
            .get("issue_number")
            .cloned()
            .unwrap_or_else(|| "0".into());
        let issue_body = ctx
            .artifacts
            .get("issue_body")
            .cloned()
            .unwrap_or_else(|| ctx.description.clone());

        // Determine workdir
        let workdir = ctx.workdir.clone().unwrap_or_else(|| ".".into());

        // Create feature branch
        let branch_name = format!("engine/issue-{}-{}", issue_number, slugify(&ctx.title));

        println!("[execute] Creating branch: {}", branch_name);
        let git_checkout = Command::new("git")
            .args(["checkout", "-b", &branch_name])
            .current_dir(&workdir)
            .output()?;

        if !git_checkout.status.success() {
            let stderr = String::from_utf8_lossy(&git_checkout.stderr);
            // Branch might already exist, try switching
            if stderr.contains("already exists") {
                Command::new("git")
                    .args(["checkout", &branch_name])
                    .current_dir(&workdir)
                    .output()?;
            } else {
                anyhow::bail!("git checkout failed: {}", stderr);
            }
        }

        // Use Claude Code to implement the changes
        let prompt = format!(
            r#"Implement the following GitHub issue in this repository.

Issue #{}: {}

{}

Requirements:
- Follow existing code patterns and conventions
- Write tests for new functionality
- Keep changes minimal and focused

Implement the changes now."#,
            issue_number, ctx.title, issue_body
        );

        println!("[execute] Running Claude Code to implement changes...");
        let result = tools.run_tool(
            "claude",
            "execute",
            &HashMap::from([
                ("prompt".into(), prompt),
                ("workdir".into(), workdir.clone()),
            ]),
        )?;

        ctx.artifacts.insert("claude_output".into(), result);

        // Push branch
        println!("[execute] Pushing branch...");
        let push = Command::new("git")
            .args(["push", "-u", "origin", &branch_name])
            .current_dir(&workdir)
            .output()?;

        if !push.status.success() {
            let stderr = String::from_utf8_lossy(&push.stderr);
            anyhow::bail!("git push failed: {}", stderr);
        }

        // Create PR
        println!("[execute] Creating pull request...");
        let pr_body = format!(
            "Closes #{}\n\n## Summary\n\nImplementation of: {}\n\n---\n\nGenerated by co-engine",
            issue_number, ctx.title
        );

        let pr_url = tools.run_tool(
            "github",
            "create_pr",
            &HashMap::from([
                ("repo".into(), ctx.repo.clone()),
                ("title".into(), ctx.title.clone()),
                ("body".into(), pr_body),
                ("head".into(), branch_name.clone()),
            ]),
        )?;

        println!("[execute] PR created: {}", pr_url);

        if let Some(number) = pr_url.rsplit('/').next() {
            ctx.artifacts.insert("pr_number".into(), number.to_string());
        }
        ctx.artifacts.insert("pr_url".into(), pr_url);
        ctx.artifacts.insert("branch".into(), branch_name);

        Ok(())
    }
}

fn slugify(s: &str) -> String {
    s.to_lowercase()
        .chars()
        .map(|c| if c.is_alphanumeric() { c } else { '-' })
        .collect::<String>()
        .split('-')
        .filter(|s| !s.is_empty())
        .collect::<Vec<_>>()
        .join("-")
        .chars()
        .take(40)
        .collect()
}
