/**
 * CO-374 — Acceptance-criteria → Playwright stub generator
 *
 * Walks work/co/CO-*.md spec files, parses ## Acceptance checklist items,
 * and emits co-web/e2e-staging/generated/from-acceptance.spec.ts with one
 * test.describe per spec and one test.fixme() per acceptance item.
 *
 * Devs fill in the TODO stubs during the PR.  CI counts fixmes:
 * Wave 4 DoD = all CO-352..359 acceptance items have non-fixme tests.
 *
 * Usage (from co-web/):
 *   node --import tsx scripts/scrum/acceptance-to-playwright.ts
 *   node --import tsx scripts/scrum/acceptance-to-playwright.ts --check
 *
 * --check: exits with code 1 if the generated file is out of date
 *   (use in CI to detect forgotten regenerations).
 */

import {
  readFileSync,
  writeFileSync,
  readdirSync,
  existsSync,
} from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, "../../..");
const WORK_CO_DIR = join(REPO_ROOT, "work/co");
const OUT_FILE = join(__dirname, "../../e2e-staging/generated/from-acceptance.spec.ts");
const CHECK_MODE = process.argv.includes("--check");

interface SpecItem {
  id: string;
  title: string;
  type: string;
  status: string;
  items: string[];
}

function parseFrontmatter(
  content: string,
): { id?: string; title?: string; type?: string; status?: string } {
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return {};
  const fm = match[1];
  const get = (key: string) => {
    const m = fm.match(new RegExp(`^${key}:\\s*["']?([^"'\n]+)["']?`, "m"));
    return m ? m[1].trim() : undefined;
  };
  return {
    id: get("id"),
    title: get("title"),
    type: get("type"),
    status: get("status"),
  };
}

function parseAcceptanceItems(content: string): string[] {
  const section = content.match(/^## Acceptance\n([\s\S]*?)(?=^##|\Z)/m);
  if (!section) return [];
  return section[1]
    .split("\n")
    .filter((l) => /^\s*- \[[ x]\]/.test(l))
    .map((l) => l.replace(/^\s*- \[[ x]\]\s*/, "").trim())
    .filter(Boolean);
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}

function escapeString(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\${/g, "\\${");
}

function collectSpecs(): SpecItem[] {
  if (!existsSync(WORK_CO_DIR)) {
    console.error(`work/co directory not found: ${WORK_CO_DIR}`);
    process.exit(1);
  }

  const files = readdirSync(WORK_CO_DIR)
    .filter((f) => /^CO-\d+\.md$/.test(f))
    .sort((a, b) => {
      const na = parseInt(a.match(/\d+/)?.[0] ?? "0", 10);
      const nb = parseInt(b.match(/\d+/)?.[0] ?? "0", 10);
      return na - nb;
    });

  const specs: SpecItem[] = [];
  for (const file of files) {
    const content = readFileSync(join(WORK_CO_DIR, file), "utf8");
    const fm = parseFrontmatter(content);
    const items = parseAcceptanceItems(content);
    if (items.length === 0) continue;
    if (!fm.id || !fm.title) continue;

    specs.push({
      id: `CO-${fm.id}`,
      title: fm.title,
      type: fm.type ?? "user-story",
      status: fm.status ?? "unknown",
      items,
    });
  }
  return specs;
}

function sanitizeForDoubleQuoteString(text: string): string {
  // Remove backslashes first, then replace remaining double quotes with single
  return text.replace(/\\/g, "").replace(/"/g, "'").trim();
}

function renderOutput(specs: SpecItem[]): string {
  const lines: string[] = [];
  lines.push(`/**`);
  lines.push(` * AUTO-GENERATED by scripts/scrum/acceptance-to-playwright.ts`);
  lines.push(` * DO NOT edit manually — regenerate with:`);
  lines.push(` *   node --import tsx scripts/scrum/acceptance-to-playwright.ts`);
  lines.push(` *`);
  lines.push(` * Each test.fixme() = one acceptance criterion from a CO-N.md spec.`);
  lines.push(` * Wave 4 DoD: all CO-352..CO-359 acceptance items have non-fixme tests.`);
  lines.push(` * Count unfilled stubs: grep -c 'test.fixme' e2e-staging/generated/from-acceptance.spec.ts`);
  lines.push(` */`);
  lines.push(``);
  lines.push(`import { test } from "@playwright/test";`);
  lines.push(``);

  for (const spec of specs) {
    const safeTitle = sanitizeForDoubleQuoteString(spec.title);
    const describeLabel = `${spec.id} — ${safeTitle}`.slice(0, 120);
    lines.push(`test.describe("${describeLabel}", () => {`);
    const seen = new Map<string, number>();
    for (const item of spec.items) {
      const escaped = escapeString(item);
      const count = seen.get(escaped) ?? 0;
      seen.set(escaped, count + 1);
      // Deduplicate by appending (#2, #3 ...) to repeat occurrences
      const suffix = count > 0 ? ` (#${count + 1})` : "";
      lines.push(`  test(\`${escaped}${suffix}\`, async ({ page: _page }) => {`);
      lines.push(`    // TODO: implement`);
      lines.push(`    test.fixme();`);
      lines.push(`  });`);
    }
    lines.push(`});`);
    lines.push(``);
  }

  return lines.join("\n");
}

const specs = collectSpecs();
const generated = renderOutput(specs);

const total = specs.reduce((sum, s) => sum + s.items.length, 0);
console.log(
  `Scanned ${specs.length} specs, ${total} acceptance items across ${specs.map((s) => s.id).join(", ").slice(0, 60)}…`,
);

if (CHECK_MODE) {
  const existing = existsSync(OUT_FILE) ? readFileSync(OUT_FILE, "utf8") : "";
  if (existing === generated) {
    console.log("✓ from-acceptance.spec.ts is up to date");
    process.exit(0);
  } else {
    console.error(
      "✗ from-acceptance.spec.ts is out of date. Run: node --import tsx scripts/scrum/acceptance-to-playwright.ts",
    );
    process.exit(1);
  }
} else {
  writeFileSync(OUT_FILE, generated, "utf8");
  console.log(`✓ Written: ${OUT_FILE}`);
  console.log(
    `  ${total} test stubs (all test.fixme()) across ${specs.length} describe blocks`,
  );
}
