#!/usr/bin/env bash
# backfill-task-archives.sh [--limit N] [--commit]
# Generates task archives retroactively for the last N merged PRs with CO-N branches.
#
# Usage:
#   scripts/backfill-task-archives.sh           # dry-run: show which tasks would be archived
#   scripts/backfill-task-archives.sh --commit  # write archives + create a single commit
#   scripts/backfill-task-archives.sh --limit 20 --commit
#
# The resulting commit is:  chore(archive): backfill CO-N..CO-M task archives
#
# Exit codes:
#   0  complete

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(git -C "$SCRIPT_DIR/.." rev-parse --show-toplevel)"
cd "$REPO_ROOT"

LIMIT=50
DO_COMMIT=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --limit)  LIMIT="$2"; shift 2 ;;
    --commit) DO_COMMIT=true; shift ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

REPO="artelonga/co"

echo "→ Fetching last $LIMIT merged PRs from $REPO..." >&2
MERGED_JSON=$(gh pr list -R "$REPO" --state merged --limit "$LIMIT" \
  --json number,headRefName,title,mergedAt)

# Extract task IDs from branch names
TASK_IDS=$(echo "$MERGED_JSON" | python3 -c "
import sys, json, re
prs = json.load(sys.stdin)
seen = set()
for p in prs:
    branch = p.get('headRefName','')
    m = re.search(r'[A-Z]+-\d+', branch)
    if m:
        tid = m.group(0)
        if tid not in seen:
            seen.add(tid)
            print(tid)
")

if [[ -z "$TASK_IDS" ]]; then
  echo "No CO-N task IDs found in the last $LIMIT merged PRs." >&2
  exit 0
fi

COUNT=$(echo "$TASK_IDS" | wc -l | tr -d ' ')
echo "  Found $COUNT task IDs to archive" >&2
echo "" >&2

MIN_ID=""
MAX_ID=""
ARCHIVED=()

while IFS= read -r tid; do
  archive_file="docs/task-archive/${tid}.json"
  if [[ -f "$archive_file" ]]; then
    echo "  skip (already exists): $tid" >&2
    continue
  fi

  echo "  archiving $tid..." >&2
  if bash "$SCRIPT_DIR/archive-task.sh" "$tid" 2>&1 | sed 's/^/    /'; then
    ARCHIVED+=("$tid")
    # Track min/max for commit message
    num=$(echo "$tid" | grep -oE '[0-9]+$')
    [[ -z "$MIN_ID" || "$num" -lt "$(echo "$MIN_ID" | grep -oE '[0-9]+$')" ]] && MIN_ID="$tid"
    [[ -z "$MAX_ID" || "$num" -gt "$(echo "$MAX_ID" | grep -oE '[0-9]+$')" ]] && MAX_ID="$tid"
  else
    echo "    Warning: archive failed for $tid" >&2
  fi
done <<< "$TASK_IDS"

echo "" >&2
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" >&2
echo "  Archived: ${#ARCHIVED[@]} tasks" >&2

if [[ ${#ARCHIVED[@]} -eq 0 ]]; then
  echo "  Nothing to commit." >&2
  exit 0
fi

if ! $DO_COMMIT; then
  echo "  Dry run — pass --commit to write a git commit" >&2
  exit 0
fi

# Stage all new/updated archive files
for tid in "${ARCHIVED[@]}"; do
  git add "docs/task-archive/${tid}.json"
done

# Also stage .gitkeep if it's new
[[ -f "docs/task-archive/.gitkeep" ]] && git add "docs/task-archive/.gitkeep" 2>/dev/null || true

COMMIT_MSG="chore(archive): backfill ${MIN_ID}..${MAX_ID} task archives

Retroactive archive for ${#ARCHIVED[@]} merged tasks.
Generated by scripts/backfill-task-archives.sh.

Co-Authored-By: Claude <noreply@anthropic.com>"

git commit -m "$COMMIT_MSG"
echo "  Committed: chore(archive): backfill ${MIN_ID}..${MAX_ID} task archives" >&2
